import mongoose, { Schema, Document } from 'mongoose';

export interface ILocation extends Document {
    _id: {
        $oid: string;
    };
    type: string;
    id?: string;
    geometry: {
        type: 'Point';
        coordinates: [number, number];
    };
    properties: {
        '@id': string;
        '@geometry'?: string;
        abandoned?: string;
        'addr:city'?: string;
        'addr:country'?: string;
        'addr:floor'?: string;
        'addr:housename'?: string;
        'addr:housenumber'?: string;
        'addr:postcode'?: string;
        'addr:street'?: string;
        'addr:suburb'?: string;
        air_conditioning?: string;
        alt_name?: string;
        amenity?: string;
        architect?: string;
        area?: string;
        'artist:wikidata'?: string;
        'artist:wikipedia'?: string;
        artist_name?: string;
        'artwork:owner'?: string;
        'artwork:sponsor'?: string;
        artwork_subject?: string;
        artwork_type?: string;
        backrest?: string;
        bar?: string;
        barrier?: string;
        beer_garden?: string;
        biergarten?: string;
        branch?: string;
        brand?: string;
        'brand:wikidata'?: string;
        'brand:wikipedia'?: string;
        brewery?: string;
        building?: string;
        'building:colour'?: string;
        'building:levels'?: string;
        'building:material'?: string;
        capacity?: string;
        cash_withdrawal?: string;
        changing_table?: string;
        'changing_table:fee'?: string;
        'changing_table:location'?: string;
        check_date?: string;
        'check_date:diet:vegetarian'?: string;
        'check_date:opening_hours'?: string;
        cocktails?: string;
        colour?: string;
        comment?: string;
        'contact:email'?: string;
        'contact:facebook'?: string;
        'contact:fax'?: string;
        'contact:instagram'?: string;
        'contact:mobile'?: string;
        'contact:phone'?: string;
        'contact:website'?: string;
        cuisine?: string;
        delivery?: string;
        'delivery:fee'?: string;
        description?: string;
        'diet:fish'?: string;
        'diet:gluten_free'?: string;
        'diet:halal'?: string;
        'diet:kosher'?: string;
        'diet:local'?: string;
        'diet:mediterranean'?: string;
        'diet:pescetarian'?: string;
        'diet:vegan'?: string;
        'diet:vegetarian'?: string;
        display?: string;
        'disused:amenity'?: string;
        dog?: string;
        'drink:coffee'?: string;
        drive_through?: string;
        ele?: string;
        email?: string;
        entrance?: string;
        fax?: string;
        fee?: string;
        fixme?: string;
        frontcooking?: string;
        gluten_free?: string;
        height?: string;
        heritage?: string;
        'heritage:operator'?: string;
        highchair?: string;
        historic?: string;
        image?: string;
        indoor?: string;
        indoor_seating?: string;
        indoor_standing?: string;
        internet_access?: string;
        kids_area?: string;
        landuse?: string;
        layer?: string;
        level?: string;
        'lfd:criteria'?: string;
        lit?: string;
        'lit:colour'?: string;
        loc_name?: string;
        lunch?: string;
        material?: string;
        memorial?: string;
        microbrewery?: string;
        mobile?: string;
        museum?: string;
        museum_type?: string;
        name?: string;
        'name:signed'?: string;
        note?: string;
        old_name?: string;
        open_air?: string;
        opening_hours?: string;
        'opening_hours:kitchen'?: string;
        'opening_hours:signed'?: string;
        'opening_hours:url'?: string;
        operator?: string;
        'operator:name'?: string;
        'operator:wikidata'?: string;
        'operator:wikipedia'?: string;
        outdoor_seating?: string;
        'payment:alipay'?: string;
        'payment:american_express'?: string;
        'payment:cards'?: string;
        'payment:cash'?: string;
        'payment:coins'?: string;
        'payment:contactless'?: string;
        'payment:credit_cards'?: string;
        'payment:cryptocurrencies'?: string;
        'payment:debit_cards'?: string;
        'payment:diners_club'?: string;
        'payment:electronic_purses'?: string;
        'payment:girocard'?: string;
        'payment:jcb'?: string;
        'payment:maestro'?: string;
        'payment:mastercard'?: string;
        'payment:nfc'?: string;
        'payment:notes'?: string;
        'payment:visa'?: string;
        'payment:visa_debit'?: string;
        phone?: string;
        'phone:mobile'?: string;
        railway?: string;
        'razed:man_made'?: string;
        'ref:isil'?: string;
        'ref:lfd'?: string;
        'ref:vatin'?: string;
        'related:wikipedia'?: string;
        reservation?: string;
        'roof:colour'?: string;
        'roof:levels'?: string;
        'roof:material'?: string;
        'roof:shape'?: string;
        room?: string;
        rooms?: string;
        sculpture_type?: string;
        self_service?: string;
        shop?: string;
        smoking?: string;
        source?: string;
        stars?: string;
        start_date?: string;
        stroller?: string;
        takeaway?: string;
        'theatre:type'?: string;
        toilets?: string;
        'toilets:access'?: string;
        'toilets:wheelchair'?: string;
        tourism?: string;
        tourism_1?: string;
        visibility?: string;
        website?: string;
        'website:menu'?: string;
        wheelchair?: string;
        'wheelchair:description'?: string;
        wikidata?: string;
        wikimedia_commons?: string;
        wikipedia?: string;
        year_of_construction?: string;
    }
}

const locationSchema: Schema = new Schema({
    _id: {
        type: mongoose.Schema.Types.ObjectId,
        required: true
    },
    type: {
        type: String,
        required: true,
        default: 'Feature',
    },
    id: {
        type: String,
        required: true
    },
    geometry: {
        type: {
            type: String,
            required: true
        },
        coordinates: {
            type: [Schema.Types.Mixed],
            required: true
        }
    },
    properties: {
        type: new Schema({
            "@geometry": String,
            "@id": {
                type: String,
                required: true
            },
            abandoned: String,
            "addr:city": String,
            "addr:country": String,
            "addr:floor": String,
            "addr:housename": String,
            "addr:housenumber": String,
            "addr:postcode": String,
            "addr:street": String,
            "addr:suburb": String,
            air_conditioning: String,
            alt_name: String,
            amenity: String,
            architect: String,
            area: String,
            "artist:wikidata": String,
            "artist:wikipedia": String,
            artist_name: String,
            "artwork:owner": String,
            "artwork:sponsor": String,
            artwork_subject: String,
            artwork_type: String,
            backrest: String,
            bar: String,
            barrier: String,
            beer_garden: String,
            biergarten: String,
            branch: String,
            brand: String,
            "brand:wikidata": String,
            "brand:wikipedia": String,
            brewery: String,
            building: String,
            "building:colour": String,
            "building:levels": String,
            "building:material": String,
            capacity: String,
            cash_withdrawal: String,
            changing_table: String,
            "changing_table:fee": String,
            "changing_table:location": String,
            check_date: String,
            "check_date:diet:vegetarian": String,
            "check_date:opening_hours": String,
            cocktails: String,
            colour: String,
            comment: String,
            "contact:email": String,
            "contact:facebook": String,
            "contact:fax": String,
            "contact:instagram": String,
            "contact:mobile": String,
            "contact:phone": String,
            "contact:website": String,
            cuisine: String,
            delivery: String,
            "delivery:fee": String,
            description: String,
            "diet:fish": String,
            "diet:gluten_free": String,
            "diet:halal": String,
            "diet:kosher": String,
            "diet:local": String,
            "diet:mediterranean": String,
            "diet:pescetarian": String,
            "diet:vegan": String,
            "diet:vegetarian": String,
            display: String,
            "disused:amenity": String,
            dog: String,
            "drink:coffee": String,
            drive_through: String,
            ele: String,
            email: String,
            entrance: String,
            fax: String,
            fee: String,
            fixme: String,
            frontcooking: String,
            gluten_free: String,
            height: String,
            heritage: String,
            "heritage:operator": String,
            highchair: String,
            historic: String,
            image: String,
            indoor: String,
            indoor_seating: String,
            indoor_standing: String,
            internet_access: String,
            kids_area: String,
            landuse: String,
            layer: String,
            level: String,
            "lfd:criteria": String,
            lit: String,
            "lit:colour": String,
            loc_name: String,
            lunch: String,
            material: String,
            memorial: String,
            microbrewery: String,
            mobile: String,
            museum: String,
            museum_type: String,
            name: String,
            "name:signed": String,
            note: String,
            old_name: String,
            open_air: String,
            opening_hours: String,
            "opening_hours:kitchen": String,
            "opening_hours:signed": String,
            "opening_hours:url": String,
            operator: String,
            "operator:name": String,
            "operator:wikidata": String,
            "operator:wikipedia": String,
            outdoor_seating: String,
            "payment:alipay": String,
            "payment:american_express": String,
            "payment:cards": String,
            "payment:cash": String,
            "payment:coins": String,
            "payment:contactless": String,
            "payment:credit_cards": String,
            "payment:cryptocurrencies": String,
            "payment:debit_cards": String,
            "payment:diners_club": String,
            "payment:electronic_purses": String,
            "payment:girocard": String,
            "payment:jcb": String,
            "payment:maestro": String,
            "payment:mastercard": String,
            "payment:nfc": String,
            "payment:notes": String,
            "payment:visa": String,
            "payment:visa_debit": String,
            phone: String,
            "phone:mobile": String,
            railway: String,
            "razed:man_made": String,
            "ref:isil": String,
            "ref:lfd": String,
            "ref:vatin": String,
            "related:wikipedia": String,
            reservation: String,
            "roof:colour": String,
            "roof:levels": String,
            "roof:material": String,
            "roof:shape": String,
            room: String,
            rooms: String,
            sculpture_type: String,
            self_service: String,
            shop: String,
            smoking: String,
            source: String,
            stars: String,
            start_date: String,
            stroller: String,
            takeaway: String,
            "theatre:type": String,
            toilets: String,
            "toilets:access": String,
            "toilets:wheelchair": String,
            tourism: String,
            tourism_1: String,
            visibility: String,
            website: String,
            "website:menu": String,
            wheelchair: String,
            "wheelchair:description": String,
            wikidata: String,
            wikimedia_commons: String,
            wikipedia: String,
            year_of_construction: String
        }),
        required: true
    }
});

export default mongoose.model<ILocation>('location', locationSchema, 'locations');
